server:
  port: 8083
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates
    encoding: UTF-8
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;instanceName=ISMS
    username: userName
    password: passWord


storage:
  ismsBucketName: isms