server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;instanceName=ISMS
    username: userName
    password: passWord


storage:
  ismsBucketName: isms